/*
 * adminlogin.java
 *
 * Created on September 4, 2009, 3:36 PM
 */

package evoting;

import connection.DBase;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author  Administrator
 */
public class adminlogin extends javax.swing.JFrame {
    
    /** Creates new form adminlogin */
    public adminlogin() {
        initComponents();
         this.getContentPane().setBackground(Color.black);
         this.setLocation(300,200);
        jLabel3.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jButton1.setForeground(Color.yellow);
        jButton1.setBackground(Color.black);
        jLabel2.setForeground(Color.white);
        jLabel2.setBackground(Color.black);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Login Page");

        jLabel6.setText("Home");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel3.setText("Administrator");

        jLabel2.setText("Access Code");

        jButton1.setText("Moderate the Voters list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(119, 119, 119)
                .addComponent(jLabel6)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jLabel2)
                    .addGap(56, 56, 56)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
        new indexpage().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String cid=jPasswordField1.getText();
        //  String cid=cid1.toString();
        if(cid.equals(null)||cid.equals("")) {
            JOptionPane.showMessageDialog(null,"Enter Access Code");
        } else {
            try {
                
                String str="Select * from adminlogin";
                
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
                Connection con = DriverManager.getConnection(DBase.url, DBase.userName, DBase.password);
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(str);
                System.out.println("connection ok");
                if(rs.next()) {
                  
                    String code1=(String)rs.getString(1);
                   
                    System.out.println("Accesscode="+code1);
                    System.out.println("Accesscode="+cid);
                    if(cid.equals(code1)) {
                        new adminopt().setVisible(true);
                        this.setVisible(false);
                    } else
                        JOptionPane.showMessageDialog(null,"Enter correct Access code");
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null,"Enter correct access code ");
                }
                
            } catch(Exception e) {
                System.out.println(e);
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
    
}
