/*
 * citizenvote.java
 *
 * Created on September 9, 2009, 6:26 PM
 */

package evoting;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.Statement;
import connection.DBase;
import java.awt.*;
import java.sql.DriverManager;
import javax.swing.*;

/**
 *
 * @author  Administrator
 */
public class citizenvote extends javax.swing.JFrame {
    
    /** Creates new form citizenvote */
    public citizenvote() {
        initComponents();
      
       //this.setLayout(new GridLayout(1,4));
        int count=4,i;
        try {
                
                String str="select * from candidatelist";
                
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
                Connection con = (Connection) DriverManager.getConnection(DBase.url, DBase.userName, DBase.password);
                Statement stmt=(Statement) con.createStatement();
                ResultSet rs=(ResultSet) stmt.executeQuery(str);
                System.out.println("connection ok");
                if(rs.next()) {
                    String cname1=(String)rs.getString(1);
                    String image=(String)rs.getString(3);
                    JRadioButton b1=new JRadioButton();
                    image="/evoting/"+image;
                    
            b1.setText(cname1);
            JLabel lb1=new JLabel();
            lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource(image))); // NOI18N
            
            jb.add(b1);
            this.add(lb1);
                
                } 
                
            } catch(Exception e) {
                System.out.println(e);
            }
            
   /*     String[] ss={"Aja","dasd","asdasd","asdas"};
       if(count==4)
       {
           JRadioButton b1=new JRadioButton();
           JRadioButton b2=new JRadioButton();
           JRadioButton b3=new JRadioButton();
           JRadioButton b4=new JRadioButton();
            b1.setText(ss[0]);
            b2.setText(ss[1]);
            b3.setText(ss[2]);
            b4.setText(ss[3]);
            jb.add(b1);
            jb.add(b2);
            jb.add(b3);
            jb.add(b4);
       }
                   */
           
       this.setSize(500,500);
     this.add(jPanel1);
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new citizenvote().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.ButtonGroup jb;
    // End of variables declaration//GEN-END:variables
    
}
