/*
 * installdb.java
 *
 * Created on September 10, 2009, 11:23 AM
 */

package evoting;

import connection.DBase;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrator
 */
public class installdb extends javax.swing.JFrame {
    
    /** Creates new form installdb */
    public installdb() {
        initComponents();
        this.setLocation(300,200);
        this.getContentPane().setBackground(Color.black);
        jLabel1.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel6.setForeground(Color.white);
        jTextField1.setForeground(Color.white);
        jButton1.setForeground(Color.yellow);
        jButton1.setBackground(Color.black);
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Access code");

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("CatholicSchoolGirls BB", 0, 14));
        jLabel2.setText("Install DB");

        jLabel6.setText("Home");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel6)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String str=jTextField1.getText();
        
        if(str.equals("ajay"))
        {
            String drop1="drop table citilogin";
             String drop2="drop table adminlogin";
String str1="create table citilogin(userid int, password varchar(244))";
 String str2="create table adminlogin(accesscode varchar(244))";  
  String str3="insert into citilogin values(133,'ajay')";
            String str4="insert into adminlogin values('a000')";
         try
        {
                      
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
    Connection con = DriverManager.getConnection(DBase.url, DBase.userName, DBase.password);
            Statement stmt=con.createStatement();
           stmt.execute(drop1);
            stmt.execute(drop2);
            stmt.execute(str1);
            stmt.execute(str2);
            stmt.executeUpdate(str3);
            stmt.executeUpdate(str4);
            
           JOptionPane.showMessageDialog(null, "Default login:\ncitilogin id= 133 pass=ajay. \nadminlogin = a000");
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Wrong Access Code");
    }//GEN-LAST:event_jButton1ActionPerformed
    }
        private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
            // TODO add your handling code here:
            
            this.setVisible(false);
            new indexpage().setVisible(true);
        }//GEN-LAST:event_jLabel6MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new installdb().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
